### ISSUE TITLE
Support payment requests

### ISSUE THREAD

**Issue by ericzorn93** [kleinjm/instacart_api#2]
Hey, I am implementing a similar TypeScript compatible NodeJS library and was wondering if you were able to reverse engineer the payment process? This way, we can expose a secure library API that will call upon Instacart v3 REST API.

**Comment by kleinjm** [comment]
Hey I haven't needed to touch the payment process for my use case yet as I've still wanted to spot check the cart before placing an order. Since this isn't a feature request on this library, I'm going to close this issue but if you need any pointers, feel free to reach out directly.

**Comment by ericzorn93** [comment]
No worries, I may add support for this in my TS implementation

**Comment by kleinjm** [comment]
@ericzorn93 actually if you could link me your typescript version that would be cool to track your progress. Thanks!

**Comment by ericzorn93** [comment]
I will once it is open sourced. I built a bot for my family that uses twilio to send messages of when the local stores have pickup or delivery times during the pandemic. I plan on removing the web server component and open sourcing the utility functions as a library at some point. However, the user will have to know how to obtain their API token and other necessary credentials for their header

**Comment by ericzorn93** [comment]
Right now if is a private repo

**Comment by ericzorn93** [comment]
Hey James, here is the beginning of my TS package - https://github.com/ericzorn93/instacart-assist. It is still currently in development
